### ISSUE TITLE
[Use case] Investigate option to generate DigitalTwin for an entire city

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/digital-twin-toolbox#14]
We should be able to generate a workflow that given predefined input data is able to generate the Digital Twin as a set of 3DTiles for a medium size city like Florence or Genova. The worflow should be characterized as follows:

## Input data
Below is a non exhaustive list of input data which we shall be prepared to handle for most common use cases to arrive at the production of an Urban DigitalTwin. For the moment we leave out IOT/Sensors and simulations.
- buildings and related urban infrasctruture data as a shapefile, citygml, cityJSON, (KML)
- point cloud data as las/laz deriving from aerial acquisitions
- point cloud data of interior, underground or smaller parts of the city as las/laz acquired mostly with handlheld devices or drones
- IFC models
- Drone Data/Photogrammetry???

## Data Preprocessing
There are a number of data preparation activities that needs to be performed. Here below we are highlightin some of them.
- Vector data conversion to polyhedron
- Point Cloud Data preprocessing including projection, sample, colorize and classification
- Drone Data processing???

## Expected output
- 3DTiles for input vector data with proper attributes
- 3DTiles for whole city from point cloud
- 3DTiles mesh from laz  from point cloud and imagery
- 3DTiles for Drone Data???

## More 
- MapStore Enhancements??? Styling, Filtering, Export???
- 2d/3d Integration? What can we do to better integrated 3D data and 2d Data?
- The final goal would be to have something similar to Cesium ION that can scale and convert seamlessly. Short term, we can have something that works on the desktop or on a single workstation

The expected output of this activity is to create a complete report that covers what follows:
- describe and documents the state-of-the art of the work done so far on the pipelines for the City of Florence
- development plan for implementing the workflow above or at least what we think it is feasible

Here below a tasklist of activities is proposed:

```[tasklist]
### Tasks
- [ ] Document current vector to 3DTiles pipeline based on Firenze use case
- [ ] Document current point cloud to 3DTiles pipeline for small part of the city based on Firenze use case
- [ ] Investigation on possible conversion optiomization for vector data (LODs, Tiling system, libraries replacements)
- [ ] Investigation on CityGML, CityJSON and KML specifications
- [ ] Investigation on possible conversion optiomization for point cloud (data management and visualization, tiling, merging)
- [ ] Investigation on point cloud classification (pythorc)
- [ ] Investigation on alternatives for 3D Tiles (Mago3D)
- [ ] Investigation on photogrammetry libraries (OpenDroneMap)
- [ ] Investigation on 3DTiles merging operations: from multiple to single tileset (cesium tools)
- [ ] Investigation on point cloud to mesh conversion
- [ ] IFC integration in the pipeline
```

**Comment by tdipisa** [comment]
@allyoucanmap I would like to finally update the status of this by further reviewing boundaries of https://github.com/geosolutions-it/digital-twin-toolbox/milestone/1
