### ISSUE TITLE
[Workflow] Review the backend structure

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/digital-twin-toolbox#17]
Currently the application uses a socket system for interactions between frontend and backend, this approach needs to be reviewed and maybe changed to a more simple approach to allow multiple user to interact with the UI.
Another aspect to take into in mind is the possibility to support an authentication system for users.

After an intial investigation we found a [full stack project templete](https://github.com/fastapi/full-stack-fastapi-template) that could cover what needed on our project:

- backend in python with an intial authentication system for user already implemented in the template
- frontend react based with user login and settings already implemented in the template
- docker compose solution that we could extend with needed libraries and containers

This project template is called [full-stack-fastapi-template](https://github.com/fastapi/full-stack-fastapi-template) is under MIT license so we can fork it and build our application on top of it. 

We will need to extend this template solution in terms of api to properly control access on assets and pipelines based on user credential, including also the possibility to upload files via UI.

It would be better to follow the react application already setup in the template project because the user pages are already implemented and it needs little adjustment on the look and feel. So it would be better to refactor the current digital-twin-toolbox UI aligning it with the look and feel of the application 

```[tasklist]
### Tasks
- [x] Review the backend DockerFile to install the following libraries: pg2b3dm, i3dm.export, pdal and py3dtiles
- [x] Review the docker-compose-file to include a celery application to manage async pipeline processes
- [x] Create assets API and UI to upload/remove following file types Shapefile (.shp.zip), GLB models (.glb) and PointCloud (.las, .laz)
- [x] Create pipelines API and UI to manage processes of conversion of an asset to 3dtiles
- [x] Create pipeline page to run and manage conversion of point shapefile assets
- [ ] https://github.com/geosolutions-it/digital-twin-toolbox/issues/25
- [x] Create pipeline page to run and manage conversion of polygon shapefile assets
- [x] Create pipeline page to run and manage conversion of point cloud assets
- [x] Review Look&Feel of the application replacing logos, favicon and titles
- [ ] Review WIKI documentation
- [ ] Port the MapStore page in the application to preview the generated tilesets
```
