### ISSUE TITLE
[UX] Improve visualization of different type of datasets

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/digital-twin-toolbox#5]
```[tasklist]
### Tasks
- [ ] Find a way to visualize the geometric error inside the viewer to make it easer to understand how it works
- [ ] The viewer could slow down with big dataset so we should find an approach to keep the visualization smooth (eg, provide only a sample of the whole dataset to the client)
- [ ] Point cloud viewer is currently empty. We should find a way to represent the point cloud data
```
